### PR TITLE
Feature/mpls ipfix

### PR DESCRIPTION
**Pull request by door7302**
Add support for MPLS fields decoding for IPFIX.

### CODE REVIEW

**Comment by lspgn** [comment]
LGTM
Thank you!
Just curious: why is there a need for a bit shift?

**Comment by door7302** [comment]
Label IPfix field includes EXP bits + S flag (it's a 24 bits field). Thus to retrieve only label I need to shift 4 bits... 
https://miro.medium.com/max/485/1*Umdp5m0NBwWmMx8TbcaJfw.png

**Comment by lspgn** [comment]
Seems that the protobuf is missing Millisecond timestamp fields when running the tests.

**Comment by door7302** [comment]
Strange. I will double check

**Pull request merged**
