### PR TITLE
feat(transport): add mTLS for Kafka

### LINKED ISSUE #363: Transport Kafka - support mTLS
**Is your feature request related to a problem? Please describe.**
our brokers use mTLS. I would like to use goflow2 with a client certificate that can be authenticated on the brokers

**Describe the solution you'd like**
Allow client certificate and key to be used in kafka TLS connection. file locations and key password should be able to be passed in as command line options

**Describe alternatives you've considered**
pmacct

### PR DESCRIPTION
**Pull request by lspgn**
Adds TLS configuration for client certificate.
Closes #363

### CODE REVIEW

**Comment by coredump17** [comment]
hi @lspgn, can we have an option to add server CA to trust also. getting error="kafka: client has run out of available brokers to talk to: tls: failed to verify certificate: x509: certificate signed by unknown authority for kafka transport" when trying to test.

**Comment by lspgn** [comment]
Try now

**Comment by coredump17** [comment]
@lspgn  
level=ERROR msg="error transporter" error="error reading server CA: read truststore.crt: file already closed for kafka transport"

**Comment by lspgn** [comment]
Ah sorry, misplaced a statement and didn't have the proper test bed

**Comment by lspgn** [comment]
Will have a look. Might be due to the PEM encoding. Would you be able to try directly in a DER binary format?

**Comment by lspgn** [comment]
This should be fixed. It was indeed missing pem decoding.

Made a test TLS server for me to test:

```
socat OPENSSL-LISTEN:9093,cert=cert.crt,key=privkey.pem,verify=0,fork STDIO
```

**Comment by coredump17** [comment]
> Will have a look. Might be due to the PEM encoding. Would you be able to try directly in a DER binary format?

yes, DER works ;).

**Comment by coredump17** [comment]
i can confirm PEM now works with your new amendment. thanks a lot!

**Pull request merged**
