### PR TITLE
producer: increase performance of sampling rate lookup

### PR DESCRIPTION
**Pull request by vincentbernat**
Formatting a string with version and domain when looking up sampling rate hurts performance. Instead, use a dedicated structure for key. It also reduces the pressure on the GC.

Before:

```
BenchmarkDecodeEncodeNetflow/with_encoding-12             158208              8611 ns/op            8178 B/op        130 allocs/op
BenchmarkDecodeEncodeNetflow/without_encoding-12          162832              7559 ns/op            8178 B/op        130 allocs/op
```

After:

```
BenchmarkDecodeEncodeNetflow/with_encoding-12             138242              8132 ns/op            8176 B/op        129 allocs/op
BenchmarkDecodeEncodeNetflow/without_encoding-12          162312              7306 ns/op            8176 B/op        129 allocs/op
```

### CODE REVIEW

**Comment by lspgn** [comment]
Thank you! Could you add the benchmarks?

Not seeing a major difference in perfs though:

```
BenchmarkTemplatesAdd
    templates_test.go:15: Creating 1 templates
    templates_test.go:15: Creating 100 templates
    templates_test.go:15: Creating 10000 templates
    templates_test.go:15: Creating 1000000 templates
    templates_test.go:15: Creating 6573939 templates
BenchmarkTemplatesAdd-4      	 6573939	       171.8 ns/op
BenchmarkTemplatesAddGet
    templates_test.go:22: Adding 1000 templates
    templates_test.go:24: Getting 1 templates
    templates_test.go:22: Adding 1000 templates
    templates_test.go:24: Getting 100 templates
    templates_test.go:22: Adding 1000 templates
    templates_test.go:24: Getting 10000 templates
    templates_test.go:22: Adding 1000 templates
    templates_test.go:24: Getting 1000000 templates
    templates_test.go:22: Adding 1000 templates
    templates_test.go:24: Getting 24474410 templates
BenchmarkTemplatesAddGet-4   	24474410	        47.66 ns/op
```

Vs

```
BenchmarkTemplatesAdd
    templates_test.go:15: Creating 1 templates
    templates_test.go:15: Creating 100 templates
    templates_test.go:15: Creating 10000 templates
    templates_test.go:15: Creating 1000000 templates
    templates_test.go:15: Creating 4606766 templates
    templates_test.go:15: Creating 7184278 templates
BenchmarkTemplatesAdd-4      	 7184278	       168.3 ns/op
BenchmarkTemplatesAddGet
    templates_test.go:22: Adding 1000 templates
    templates_test.go:24: Getting 1 templates
    templates_test.go:22: Adding 1000 templates
    templates_test.go:24: Getting 100 templates
    templates_test.go:22: Adding 1000 templates
    templates_test.go:24: Getting 10000 templates
    templates_test.go:22: Adding 1000 templates
    templates_test.go:24: Getting 1000000 templates
    templates_test.go:22: Adding 1000 templates
    templates_test.go:24: Getting 24551028 templates
BenchmarkTemplatesAddGet-4   	24551028	        46.35 ns/op
```

**Comment by vincentbernat** [comment]
Well, you get the performance increase too (~2%). Moreover, because there is an allocation less, this reduces GC pressure.

**Comment by lspgn** [comment]
Oh yes, it's a good improvement. Was just hoping to dive into the benchmarks to understand, if easy to add? Otherwise I'll just merge.

**Comment by vincentbernat** [comment]
That was an end-to-end benchmark I have in Akvorado.

**Pull request merged**
