### PR TITLE
docs: added softflowd-agent docs

### PR DESCRIPTION
**Pull request by superstes**
As I'm currently working on a project that uses the softflowd netflow-agent - I created a short documentation on how to configure it.

### CODE REVIEW

**Review by lspgn — CHANGES_REQUESTED** [review]
Thank you for this contribution. My comments below:

* softflowd does not seem to have a capital letter
* it's lacking a small description
* `/usr/sbin/softflowd` -> `$ softflowd` for consistency
* there are many options you added to the CLI: I would suggest removing some since we are linking to the doc
* I don't think the service creation is necessary here

**Comment by superstes** [comment]
@lspgn Sure - the service example was too much. That's why I converted the PR to a draft (:

Sorry for the multiple commits - but your feedback should be covered.

**Review by lspgn — CHANGES_REQUESTED** [review]
Doc link should be `https://github.com/irino/softflowd/wiki/softflowd` (can remove repository)

Description should indicate it does NetFlow/IPFIX.

`127.0.0.1` -> `10.0.0.1` to match other examples

Service section should be removed.

**Comment by lspgn** [comment]
Added softflowd with https://github.com/netsampler/goflow2/pull/272

**Pull request closed without merging**
