### PR TITLE
Add metrics for detecting missing flows/packets

### PR DESCRIPTION
**Pull request by AlexandreYang**
## What this PR does

Add metrics for detecting missing flows/packets

## Motivation

Detecting missing flows/packets can:
- give visibility on how reliable is the netflow data since high volume of missing flows/packets makes netflow data less reliable
- help sizing (cpu/mem) the netflow collector server, high number of missing flows might mean the server doesn't have enough resources (cpu for example)

Why not process in later stage of the pipeline (collector, database, etc) ?

It's harder to detect missing flows/packets in later stages since not all sequence number are available in later stage of the pipeline. For example NetFlow9/IPIFX 
- Template FlowsSet
- Options Template/Data FlowSet
are not present in later stages.

## How unordered packets arrival is handled?

The implementation in the PR doesn't rely on packets arriving in order (ordered sequence number).

When unordered packets arrives, the reported missing flows/packets might be slightly wrong for a short moment, but it will "self correct" when subsequent packets arrive. The `MissingFlowsTracker.counters` tracks the number of flows/packets, and the flows/packets_missing metric is the different between the current `sequence number - tracked flows/packets counter` ([code](https://github.com/netsampler/goflow2/pull/161/files#diff-d37f6561df33631e40a6f0d1c8ee1dc8737102d4f782594bc195af9bda3f21f5R32)).

This test might help illustrate the case: As you can see in this test https://github.com/netsampler/goflow2/pull/161/commits/45b6b95ea0aa1d14d842574f979d0ca7f5bb376f the packet P5 is received before the packet P4, but we will get the right number of packets lost of 10 (packet P2 is lost in this test).

## Performance  / Memory

The implementation uses a lock with simple `O(1)` operations, see `countMissing` method, that shouldn't impact performance in visible way.

We use `counters   map[string]int64 ` to keep track of flows/packets/samples for each distinct:
- samplerAddress/obsDomain (netflow9
- samplerAddress/engineType/engineId (netflow5)
- samplerAddress/agent/subAgentId (sflow)
that should be in limited number.

## Related Issue

https://github.com/netsampler/goflow2/issues/116

### CODE REVIEW

**Comment by AlexandreYang** [comment]
Hi @lspgn , what do you think about this approach of detecting missing flows/packets/samples? Can I have a review?

**Comment by lspgn** [comment]
Hi @AlexandreYang 
Thank you for this PR.

JFYI: I am actively developing [v2](https://github.com/netsampler/goflow2/tree/app/refactor) which changes the Prometheus metrics quite a bit. You may want to have a look

Could you check build? Seems to have failed the tests.

Are you using this in production?

I would suggest to monitor for UDP dropped packets overall rather than in the application. Networks can be lossy.

In regards to the implementation:
My main concern is that it makes an assumption on the network that the packets arrive in order.
This is the reason I would prefer checking in the later stages and I am not convinced it would be useful here.
In the case of some deployments, load-balancing (eg: if random, not hashed with sFlow) could also increase the counter

A possible solution (need to think on the details) would be an online sum that has some kind of windowing that could be summarized with:

```
(diff + 2*start_seq) * (diff + 1) / 2 = start_seq + (start_seq + 1) + ... + (start_seq + diff)
```

Periodically scanned, if it grows, it would mean packets are getting dropped.

**Comment by AlexandreYang** [comment]
Hi @lspgn, thanks for having a look at this PR.

> JFYI: I am actively developing [v2](https://github.com/netsampler/goflow2/tree/app/refactor) which changes the Prometheus metrics quite a bit. You may want to have a look

Great to see those refactoring/improvements. Indeed prometheus metrics moved a bit.

> Could you check build? Seems to have failed the tests.

Indeed, a test is failing, I think this should fix it: https://github.com/netsampler/goflow2/pull/161/commits/278d33a51a2d22427578048b065847a63302c721

Is it possible to run CI on this branch? 

> Are you using this in production?

The intent is to use this in production, but it's not in prod yet. I'm going to test in our staging environment today/tomorrow.

> I would suggest to monitor for UDP dropped packets overall rather than in the application. Networks can be lossy.

I curious about this, do you have an example of where and how (what kind of tool) to monitor UDP loss reliably? (without relying on sequence number)

> My main concern is that it makes an assumption on the network that the packets arrive in order.

Actually, the implementation in the PR doesn't rely on packets arriving in order (ordered sequence number).

When unordered packets arrives, the reported missing flows/packets might be slightly wrong for a short moment, but it will "self correct" when subsequent packets arrive. The `MissingFlowsTracker.counters` tracks the number of flows/packets, and the flows/packets_missing metric is the different between the current `sequence number - tracked flows/packets counter` ([code](https://github.com/netsampler/goflow2/pull/161/files#diff-d37f6561df33631e40a6f0d1c8ee1dc8737102d4f782594bc195af9bda3f21f5R32)).

I just added this test, that might help illustrate the case: As you can see in this test https://github.com/netsampler/goflow2/pull/161/commits/45b6b95ea0aa1d14d842574f979d0ca7f5bb376f the packet P5 is received before the packet P4, but we will get the right number of packets lost of 10 (packet P2 is lost in this test).

> A possible solution (need to think on the details) would be an online sum that has some kind of windowing that could be summarized with.

Happy to hear if you think there is a better alternative way :)

Note, the way it's implemented in this PR, we consider as "window" the entire duration since the last sequence number reset. The flows_missing/packets_missing/samples_missing metric is reporting the number of flows/packets/samples missing since the last sequence reset (ref sequence reset logic in code).

**Comment by lspgn** [comment]
> I curious about this, do you have an example of where and how (what kind of tool) to monitor UDP loss reliably? (without relying on sequence number)

I don't think flows should be used to monitor loss. Probably better to setup NetNORAD or a system with a predictable amount of packets per time interval. I originally thought you wanted to debug flow errors as you mentioned sizing, in which case the kernel UDP queue drops metric should reflect more a lack of CPU. 

Forgot to add that UDP can also be duplicated and corrupted.
IMHO the counter returned does not really give a good information to determine a loss as well (example below).
Finally, I wouldn't trust the vendors to make this an accurate field as well.

```
| seq | ctr | missing |
|-----|-----|---------|
| 10  | 10  | 0       |
| 11  | 11  | 0       |
| 16  | 12  | 4       |
| 12  | 13  | -1      |
| 15  | 14  | 1       |
| 14  | 15  | -1      |
| 14  | 16  | -2      |
| 14  | 17  | -3      |
```

Overall, I don't think this feature should be added.

**Pull request closed without merging**
