### PR TITLE
decoder: fix netflow flowsets decoding

### PR DESCRIPTION
**Pull request by TCheruy**
Only last Flowset of Netflow packets is currently decoded (in v2), this PR ensure that all Flowsets are decoded

### CODE REVIEW

**Comment by AlexandreYang** [comment]
Hey @lspgn, Do you mind have a look at this possible bug? Looks like related in the recent v2 refactoring.

**Comment by TCheruy** [comment]
The for loop in `DecodeMessageCommon` can indeed be moved to `DecodeMessageNetflow` and `DecodeMessageIPFIX`
https://github.com/netsampler/goflow2/blob/34a0c1618e6fcf0d509c4553b3236b4aa85c71ca/decoders/netflow/netflow.go#L288
but it will also lead to a signature change (since the `size` argument won't be needed in `DecodeMessageCommon` anymore)
Also this is common code to NetFlow and IPFIX so it makes sense to me to have the for loop in `DecodeMessageCommon`

**Comment by mscastanho** [comment]
I've recently started experimenting with the project and went straight into the v2 code. Then I just realized I was getting way less flows than expected (looking at the raw IPFIX packets). Even packets containing 3-4 flows were always generating flowsets with a single flow on them.

So looks like this is the problem =)

Haven't tested the fix in this PR yet, though.

**Review by lspgn — APPROVED** [review]

**Comment by lspgn** [comment]
Had a better look at it. Thank you very much for raising this!

I'm really not sure how I badly missed it when splitting the code from the v1... Turns out I was testing with single item flowsets:

https://github.com/netsampler/goflow2/blob/9287e0552896c46181bd9e8204479e92a82de4b8/decoders/netflow/netflow.go#L520-L524

I pushed a commit that split the function (had to change signature indeed)

**Pull request merged**
