### PR TITLE
decoders: replace binary.Read with a version without reflection and allocations

### PR DESCRIPTION
**Pull request by vincentbernat**
See #140. Not really tested. Still need to get rid of `bytes.Buffer`.

### CODE REVIEW

**Comment by vincentbernat** [comment]
By using the `Next()` method on `bytes.Buffer`, we can avoid allocating arrays on the heap. This provides a 33% speedup with sFlow. This is a far bigger win than not using reflection (as I suppose the paths where reflection were used were not that important).

**Comment by vincentbernat** [comment]
I may have introduced a regression, let me investigate!

**Comment by vincentbernat** [comment]
OK for now. I have fixed the bug. Previously, when we provide `*[]uint8`, this was done with reflection. My bug was I didn't handle this case (only `[]uint8`) and it's easy to miss because some callers provide a pointer to the slice instead of just the slice. I have fixed them to just provide the slice, but it shows this change may be a bit dangerous.

**Comment by lspgn** [comment]
Added benchmark:

```
BenchmarkBinaryReadIntegerBase-4         	85853754	        14.17 ns/op
BenchmarkBinaryReadIntegerComparison-4   	21691910	        48.44 ns/op
BenchmarkBinaryReadByteBase-4            	98613631	        12.20 ns/op
BenchmarkBinaryReadBytesBase-4           	77762986	        14.36 ns/op
BenchmarkBinaryReadBytesComparison-4     	23859307	        46.16 ns/op
BenchmarkBinaryReadUintsBase-4           	38840542	        29.84 ns/op
BenchmarkBinaryReadUintsComparison-4     	14845839	        76.42 ns/op
```

**Comment by lspgn** [comment]
Will integrate it with v2 as well.

**Pull request merged**
