### PR TITLE
chore(decoders.sflow): Cleanup constant definitions and use switch statements

### PR DESCRIPTION
**Pull request by srebhan**
The current `FORMAT_*` constant definitions in the sFlow decoder mixes definitions for opaque `sample_data` and `flow_data` as defined in the [sFlow datagram spec](https://sflow.org/SFLOW-DATAGRAM5.txt) and [sFlow datastructs spec](https://sflow.org/SFLOW-STRUCTS5.txt).
Those definitions reference different things and the current code reuses the definitions in a very confusing way, making it difficult to relate the specification(s) to the code.

The present PR cleans the constant definitions and splits them into their respective meaning. The old `FORMAT_*` constants are not used anymore internally and are only kept for external users' compatibility.
Additionally, the PR switches to `switch` statements in the decoding functions as those are more readable and simplifies code a bit.

The PR does NOT apply any functional changes and is for cleanup only.

### CODE REVIEW

**Comment by lspgn** [comment]
Thank you! will have a look.
I wouldn't be too worried about removing instead of deprecating (I may forget to do it next large version bump).

**Comment by srebhan** [comment]
@lspgn it's your say, I can also remove the deprecated consts... :-) Shall I?

I do have two more PRs in the pipe, one adding parsing the ETH flow record and one adding discard support, but need to wait on this one as I base them off this PR...

**Comment by lspgn** [comment]
Yes please go ahead with the removal! Thank you :) 

For the other, would you be able to add tests and provide me with a packet capture?

**Comment by srebhan** [comment]
Deprecated constants removed. After this PR is merged, I will put up the other two, including unit-tests of course. :-)

**Comment by srebhan** [comment]
@lspgn is there anything I can do to get this merged?

**Comment by lspgn** [comment]
@srebhan I just need to find some time to take care of it :), thank you

**Review by lspgn — APPROVED** [review]

**Comment by lspgn** [comment]
I'm sorry it took so long to review.
I just merged the three PRs. Thank you for the great work.

**Pull request merged**
