### PR TITLE
utils: copy payload before accepting another UDP packet

### PR DESCRIPTION
**Pull request by vincentbernat**
In d1e1ace3186d ("Allow Flow Routines to be cancellable (#40)"), the
payload was passed to another goroutine and erased by the next packet
to be received if the goroutine did not process it fast enough. Make
a copy before passing it to the goroutine to fix that.

### CODE REVIEW

**Comment by lspgn** [comment]
Thank for catching it
cc @mariomac for visibility

**Comment by lspgn** [comment]
Note to self: probably would be good to use [`sync.Pool`](https://pkg.go.dev/sync#Pool) for this

**Comment by vincentbernat** [comment]
> Note to self: probably would be good to use [`sync.Pool`](https://pkg.go.dev/sync#Pool) for this

I was thinking the same thing. There are a lot of small objects allocated. The original payload should be part of this to avoid copying it once we know the size.

**Comment by mariomac** [comment]
Good catch! Thanks and sorry for the "bug introduction".

**Comment by vincentbernat** [comment]
I have looked into using a sync pool, but this is not easy as the payload is then sent to a worker pool through another channel. We would need to abstract a bit the pool to use it across module boundaries.

**Comment by vincentbernat** [comment]
I was thinking about a simpler approach, which could be more performant and less error-prone. Instead of dispatching UDP packets to workers, we could make workers read from the UDP socket directly. This way, we don't need to copy the packet around. Another optimisation would be to have one socket for each worker (this would mandate the use of `SO_REUSEPORT`), this is known to be more efficient than sharing a socket between multiple threads.

**Pull request merged**
